Fix styling in sus

diff --git a/sus b/sus
--- a/sus
+++ b/sus
@@ -2,36 +2,31 @@
 
 set -e
 
-SUSDIR=$HOME/Documents/org/
-SUSTAR=$SUSDIR/sus.tar
-SUSENCRYPT=$SUSDIR/sus.tar.gpg
-NEWSUS=$(date +%Y-%m-%d).txt
-RECIPIENT=34E8F9595132FE4897B3CF88FA2A15E74BB05411
+susdir=$HOME/Documents/org/
+sustar="${susdir}/sus.tar"
+susencrypt="${susdir}/sus.tar.gpg"
+sussy_file=$(date +%Y-%m-%d).txt
+recipient=34E8F9595132FE4897B3CF88FA2A15E74BB05411
 
-RNG=$(shuf -i 1-10 -n 1)
+rng=$(shuf -i 1-10 -n 1)
 
-if [ $RNG -eq 1 ]; then
-	SUSBACK=${SUSENCRYPT}-$(date +%Y-%m-%d_%H-%M)
-	cp $SUSENCRYPT $SUSBACK
-	echo Backing up to ${SUSBACK}...
+#
+if [ $rng -eq 1 ]; then
+	susback="${susencrypt}-$(date +%Y-%m-%d_%H-%M)"
+	cp "$susencrypt" "$susback"
+	echo "Backing up to ${susback}..."
 fi
 
-gpg -d $SUSENCRYPT > $SUSTAR
-tar xf $SUSTAR -C $SUSDIR
-if [ ! -f $SUSNEW ]; then
-	echo "
-#comment
-vim:expandtab:softtabstop=2:tabstop=2:shiftwidth=2" > $SUSNEW
-fi
+gpg -d "$susencrypt" > "$sustar"
+tar xf "$sustar" -C "$susdir"
 
-$EDITOR $SUSDIR/sus/$NEWSUS \
-	&& \
-tar cf $SUSDIR/sus.tar --directory=$SUSDIR ./sus
-rm -rf ${SUSTAR}.gpg
-gpg -e --recipient $RECIPIENT $SUSTAR && \
-rm -rf $SUSTAR && \
-rm -rf $SUSDIR/sus || (echo SOMETHING FAILED && \
+$EDITOR "${susdir}/sus/${sussy_file}"
+tar cf "${susdir}/sus.tar" --directory="${susdir}" ./sus
+rm -rf "${sustar}.gpg"
+gpg -e --recipient "$recipient" "$sustar"
+rm -rf "$sustar"
+rm -rf "${susdir}/sus" || (echo "SOMETHING FAILED" && \
 echo tar with \
-tar cf $SUSDIR/sus.tar --directory=$SUSDIR ./sus && \
+tar cf "${susdir}/sus.tar" --directory="${susdir}" ./sus && \
 echo re-encrypt with \
-gpg -e --recipient $RECIPIENT $SUSTAR)
+gpg -e --recipient "$recipient" "$sustar")
